import { mutation } from "./_generated/server";

const toolsData = [
  {
    name: "ChatGPT",
    slug: "chatgpt",
    description: "OpenAI's conversational AI model capable of generating human-like text, answering questions, and assisting with various tasks.",
    longDescription: "ChatGPT is a large language model developed by OpenAI, built on the GPT-4 architecture. It can engage in nuanced conversations, write code, create content, analyze data, and assist with complex problem-solving. With plugins and browsing capabilities, it serves as a versatile AI assistant for both personal and professional use.",
    category: "Writing",
    tags: ["Chatbot", "LLM", "Assistant"],
    websiteUrl: "https://chat.openai.com",
    logoUrl: "https://logos.hunter.io/chat.openai.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with GPT-3.5. Plus $20/mo for GPT-4, Team $25/user/mo, Enterprise custom pricing.",
    upvotes: 1542,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["GPT-4 and GPT-4o models", "Code interpreter and data analysis", "DALL-E image generation", "Web browsing and plugins", "Custom GPTs builder", "Voice conversations"],
    useCases: ["Content writing and editing", "Code generation and debugging", "Research and data analysis", "Language translation and learning"],
    pros: ["Extremely versatile and capable", "Large plugin ecosystem", "Regular model updates", "Strong coding abilities"],
    cons: ["Can hallucinate facts", "Free tier limited to GPT-3.5", "Context window limitations on long conversations"],
    platforms: ["Web", "iOS", "Android", "Desktop", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/OpenAI",
    githubUrl: "https://github.com/openai",
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "An AI program and service created by Midjourney, Inc. that generates images from natural language descriptions.",
    longDescription: "Midjourney is one of the leading AI image generators, known for its artistic and photorealistic outputs. Operating through Discord, it uses advanced diffusion models to transform text prompts into stunning visual art. The v6 model delivers exceptional detail, coherence, and prompt following.",
    category: "Image",
    tags: ["Generative Art", "Design", "Creative"],
    websiteUrl: "https://www.midjourney.com",
    logoUrl: "https://logos.hunter.io/midjourney.com",
    pricing: "Paid",
    pricingDetails: "Basic $10/mo (200 images), Standard $30/mo (unlimited relaxed), Pro $60/mo (fast hours + stealth mode).",
    upvotes: 1230,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["V6 model with exceptional detail", "Style tuning and references", "Zoom out and pan controls", "Vary region inpainting", "Describe image to prompt", "High-res upscaling"],
    useCases: ["Concept art and illustration", "Marketing and social media visuals", "Product mockups and prototyping", "Book covers and editorial art"],
    pros: ["Best-in-class artistic quality", "Consistent style outputs", "Active community and support", "Regular major model updates"],
    cons: ["Requires Discord to use", "No free tier available", "Limited editing capabilities"],
    platforms: ["Web"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/midaborjourney",
    discordUrl: "https://discord.gg/midjourney",
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "An AI pair programmer that offers autocomplete-style suggestions as you code.",
    longDescription: "GitHub Copilot uses OpenAI's Codex model to suggest code completions, entire functions, and even complex algorithms as you type. It integrates directly into popular IDEs and understands context from your codebase, comments, and coding patterns to deliver highly relevant suggestions.",
    category: "Coding",
    tags: ["Development", "Code Assistant", "Productivity"],
    websiteUrl: "https://github.com/features/copilot",
    logoUrl: "https://logos.hunter.io/github.com",
    pricing: "Paid",
    pricingDetails: "Individual $10/mo, Business $19/user/mo, Enterprise $39/user/mo. Free for verified students and open-source maintainers.",
    upvotes: 980,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["Real-time code suggestions", "Multi-line function completion", "Chat interface for code questions", "CLI assistance", "Pull request summaries", "Knowledge base integration"],
    useCases: ["Faster code writing and prototyping", "Learning new languages and frameworks", "Writing tests and documentation", "Code refactoring and optimization"],
    pros: ["Deep IDE integration", "Understands project context", "Supports 50+ languages", "Free for students"],
    cons: ["Subscription required for full access", "Suggestions can be incorrect", "Privacy concerns with code telemetry"],
    platforms: ["Desktop", "Web"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/GitHubCopilot",
    githubUrl: "https://github.com/features/copilot",
  },
  {
    name: "Notion AI",
    slug: "notion-ai",
    description: "An AI assistant integrated into Notion that helps you write, brainstorm, edit, and summarize.",
    longDescription: "Notion AI brings AI capabilities directly into the Notion workspace, allowing users to generate content, summarize documents, translate text, and brainstorm ideas without leaving their notes. It understands the context of your workspace and can pull insights from your existing pages.",
    category: "Productivity",
    tags: ["Writing", "Notes", "Workspace"],
    websiteUrl: "https://www.notion.so/product/ai",
    logoUrl: "https://logos.hunter.io/notion.so",
    pricing: "Paid",
    pricingDetails: "AI add-on $10/member/mo on top of Notion plan. Free Notion plan available, Plus $10/mo, Business $18/mo.",
    upvotes: 850,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI writing and editing within Notion", "Document summarization", "Translation to 14+ languages", "Brainstorming and ideation", "Q&A across workspace", "Action item extraction"],
    useCases: ["Meeting notes and summaries", "Content drafting and editing", "Project documentation", "Knowledge management"],
    pros: ["Seamless workspace integration", "Context-aware responses", "Works with existing Notion data", "Clean intuitive interface"],
    cons: ["Requires separate AI subscription", "Only works within Notion", "Limited compared to standalone AI tools"],
    platforms: ["Web", "iOS", "Android", "Desktop"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/NotionHQ",
  },
  {
    name: "Runway",
    slug: "runway",
    description: "Applied AI research company shaping the next era of art, entertainment and human creativity.",
    longDescription: "Runway is a leading AI video generation platform that offers Gen-3 Alpha, one of the most advanced text-to-video and image-to-video models available. It also provides a comprehensive suite of AI-powered video editing tools including background removal, motion tracking, and inpainting.",
    category: "Video",
    tags: ["Video Editing", "Generative Video", "Creative"],
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://logos.hunter.io/runwayml.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with 125 credits. Standard $12/mo (625 credits), Pro $28/mo (2250 credits), Unlimited $76/mo.",
    upvotes: 720,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["Gen-3 Alpha text-to-video", "Image-to-video generation", "AI-powered green screen", "Motion tracking and brush", "Inpainting and outpainting", "Audio and subtitle tools"],
    useCases: ["Short film and music video creation", "Social media content production", "Product demos and explainers", "Visual effects and post-production"],
    pros: ["Industry-leading video generation", "Comprehensive editing toolkit", "Fast generation times", "Professional quality output"],
    cons: ["Credit system can be expensive", "Long video generation limited", "Requires learning curve"],
    platforms: ["Web", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/runaborwayml",
  },
  {
    name: "Claude",
    slug: "claude",
    description: "A next-generation AI assistant built for work and trained to be safe, accurate, and secure.",
    longDescription: "Claude by Anthropic is designed to be helpful, harmless, and honest. It excels at long-form content, analysis, coding, and nuanced conversations. With a 200K context window, Claude can process entire codebases, long documents, and complex datasets in a single conversation.",
    category: "Writing",
    tags: ["Chatbot", "LLM", "Assistant"],
    websiteUrl: "https://claude.ai",
    logoUrl: "https://logos.hunter.io/anthropic.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with Claude 3.5 Sonnet. Pro $20/mo for Claude Opus, Team $25/user/mo, Enterprise custom pricing.",
    upvotes: 1100,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["200K context window", "Artifacts for code and documents", "Vision and image analysis", "Advanced reasoning and analysis", "Projects and knowledge bases", "Computer use capabilities"],
    useCases: ["Long document analysis and summarization", "Code writing and review", "Research and report generation", "Creative writing and brainstorming"],
    pros: ["Massive context window", "Excellent at following instructions", "Strong safety guardrails", "Superior at nuanced analysis"],
    cons: ["Can be overly cautious", "Slower than some competitors", "No web browsing capability"],
    platforms: ["Web", "iOS", "Android", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/AnthropicAI",
    githubUrl: "https://github.com/anthropics",
  },
  {
    name: "Synthesia",
    slug: "synthesia",
    description: "An AI video generation platform that enables you to turn text into video in minutes.",
    longDescription: "Synthesia allows users to create professional videos with AI avatars that speak in over 130 languages. No camera, mic, or studio needed. It's widely used for corporate training, onboarding, and marketing videos, offering a library of customizable templates and realistic avatar presenters.",
    category: "Video",
    tags: ["Avatars", "Text-to-Video", "Marketing"],
    websiteUrl: "https://www.synthesia.io",
    logoUrl: "https://logos.hunter.io/synthesia.io",
    pricing: "Paid",
    pricingDetails: "Starter $22/mo (120 minutes/year), Creator $67/mo (360 minutes/year), Enterprise custom pricing.",
    upvotes: 640,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["160+ AI avatar presenters", "130+ languages and accents", "Custom avatar creation", "Screen recording integration", "Brand kit and templates", "One-click video translation"],
    useCases: ["Corporate training videos", "Employee onboarding", "Product demos and tutorials", "Multilingual marketing content"],
    pros: ["No filming equipment needed", "Rapid video production", "Massive language support", "Professional looking output"],
    cons: ["Avatar movements can feel stiff", "Limited creative flexibility", "Expensive for high volume"],
    platforms: ["Web", "API"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/synthesiaIO",
  },
  {
    name: "Jasper",
    slug: "jasper",
    description: "An AI copilot for enterprise marketing teams who want better outcomes, not just faster outputs.",
    longDescription: "Jasper is an AI marketing platform designed for enterprise teams. It offers brand voice consistency, campaign management, and collaborative workflows. With integrations into popular marketing tools, it helps teams create on-brand content at scale across all channels.",
    category: "Writing",
    tags: ["Marketing", "Copywriting", "SEO"],
    websiteUrl: "https://www.jasper.ai",
    logoUrl: "https://logos.hunter.io/jasper.ai",
    pricing: "Paid",
    pricingDetails: "Creator $49/mo (1 seat), Pro $69/mo (1 seat), Business custom pricing for teams.",
    upvotes: 590,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Brand voice and style guide", "Campaign brief to content", "50+ content templates", "SEO optimization tools", "Browser extension", "Team collaboration workflows"],
    useCases: ["Marketing copy and campaigns", "Blog posts and articles", "Social media content", "Email marketing sequences"],
    pros: ["Enterprise-grade brand consistency", "Strong template library", "Good team collaboration", "SEO integration"],
    cons: ["Expensive for individuals", "Output quality varies", "Learning curve for full features"],
    platforms: ["Web", "Chrome Extension", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/heyjasperai",
  },
  {
    name: "Cursor",
    slug: "cursor",
    description: "The AI Code Editor. Built to make you extraordinarily productive.",
    longDescription: "Cursor is a fork of VS Code that deeply integrates AI into every aspect of the coding experience. It features an AI chat that understands your entire codebase, inline code generation, multi-file editing with a single prompt, and intelligent auto-complete that predicts your next edit.",
    category: "Coding",
    tags: ["IDE", "Development", "Code Assistant"],
    websiteUrl: "https://cursor.sh",
    logoUrl: "https://logos.hunter.io/cursor.sh",
    pricing: "Freemium",
    pricingDetails: "Free tier with 2000 completions. Pro $20/mo (unlimited), Business $40/user/mo with admin controls.",
    upvotes: 890,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["Codebase-aware AI chat", "Multi-file editing from prompts", "Tab autocomplete predictions", "Inline diff editing", "Terminal command generation", "Custom docs indexing"],
    useCases: ["Full-stack application development", "Code refactoring and migration", "Bug fixing and debugging", "Learning new codebases quickly"],
    pros: ["VS Code compatible extensions", "Understands entire project context", "Fast inline completions", "Natural language to code edits"],
    cons: ["Separate app from VS Code", "Pro plan needed for best models", "Can be resource intensive"],
    platforms: ["Desktop"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/cursor_ai",
  },
  {
    name: "Descript",
    slug: "descript",
    description: "There's a new way to make video and podcasts. A good way.",
    longDescription: "Descript is an all-in-one video and podcast editor that lets you edit media by editing text. Its AI features include automatic transcription, filler word removal, eye contact correction, and AI voice cloning for overdubs. It makes professional video editing accessible to non-editors.",
    category: "Video",
    tags: ["Audio", "Editing", "Transcription"],
    websiteUrl: "https://www.descript.com",
    logoUrl: "https://logos.hunter.io/descript.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (1 hour transcription). Hobbyist $24/mo, Pro $33/mo, Enterprise custom pricing.",
    upvotes: 710,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Edit video by editing text", "AI filler word removal", "Eye contact correction", "Voice cloning for overdubs", "Automatic transcription", "Screen recording built-in"],
    useCases: ["Podcast production and editing", "YouTube video creation", "Course and tutorial production", "Meeting recording and highlights"],
    pros: ["Intuitive text-based editing", "Excellent transcription accuracy", "All-in-one audio and video", "Generous free tier"],
    cons: ["Performance can lag with long files", "Advanced features require Pro plan", "Export options limited on free tier"],
    platforms: ["Web", "Desktop"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/DescriptApp",
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    description: "Perplexity AI is an AI-chat-based conversational search engine that answers queries using natural language predictive text.",
    longDescription: "Perplexity combines the power of large language models with real-time web search to provide sourced, accurate answers. It cites every claim with links, making it ideal for research. The Pro Search feature performs multi-step reasoning to answer complex questions thoroughly.",
    category: "Productivity",
    tags: ["Search", "Research", "LLM"],
    websiteUrl: "https://www.perplexity.ai",
    logoUrl: "https://logos.hunter.io/perplexity.ai",
    pricing: "Freemium",
    pricingDetails: "Free with basic search. Pro $20/mo for unlimited Pro searches, file uploads, and GPT-4/Claude access.",
    upvotes: 1050,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["Real-time web search with citations", "Pro Search multi-step reasoning", "File and image analysis", "Collections for organizing research", "API access", "Focus modes for different sources"],
    useCases: ["Academic and professional research", "Fact-checking and verification", "Market research and analysis", "Quick answers with sources"],
    pros: ["Always cites sources", "Real-time web information", "Clean minimal interface", "Multi-model access on Pro"],
    cons: ["Free tier has search limits", "Can be slow on complex queries", "Sources not always perfectly relevant"],
    platforms: ["Web", "iOS", "Android", "Chrome Extension", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/peraborplexity_ai",
  },
  {
    name: "V0 by Vercel",
    slug: "v0",
    description: "Generate UI with simple text prompts. v0 is a generative user interface system by Vercel.",
    longDescription: "V0 generates production-ready React components using shadcn/ui and Tailwind CSS from natural language descriptions. It creates responsive, accessible UI code that can be directly copied into Next.js projects. The iterative editing flow lets you refine designs through conversation.",
    category: "Coding",
    tags: ["UI", "Design", "React"],
    websiteUrl: "https://v0.dev",
    logoUrl: "https://logos.hunter.io/vercel.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with 200 generations/mo. Premium $20/mo for unlimited generations and priority access.",
    upvotes: 820,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["Text-to-UI generation", "shadcn/ui and Tailwind output", "Iterative design refinement", "Copy-paste ready code", "Responsive design output", "Component library integration"],
    useCases: ["Rapid UI prototyping", "Landing page creation", "Component library building", "Design system exploration"],
    pros: ["Production-ready code output", "Uses popular frameworks", "Fast iteration cycles", "Great for prototyping"],
    cons: ["Limited to React/Next.js stack", "Complex layouts need refinement", "Generation limits on free tier"],
    platforms: ["Web"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/v0",
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    description: "The most realistic AI speech software. Create lifelike voiceovers for your content or use our AI voice generator as an easy-to-use text to speech reader.",
    longDescription: "ElevenLabs offers the most natural-sounding AI text-to-speech technology available. It supports voice cloning from just a few minutes of audio, real-time voice changing, and multilingual speech generation. Used by creators, publishers, and enterprises for professional voice content at scale.",
    category: "Audio",
    tags: ["Voice", "Text-to-Speech", "Cloning"],
    websiteUrl: "https://elevenlabs.io",
    logoUrl: "https://logos.hunter.io/elevenlabs.io",
    pricing: "Freemium",
    pricingDetails: "Free tier (10K characters/mo). Starter $5/mo, Creator $22/mo, Pro $99/mo, Scale $330/mo.",
    upvotes: 930,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["Ultra-realistic text-to-speech", "Voice cloning from audio samples", "29+ language support", "Real-time voice changer", "Audio dubbing and translation", "Voice library marketplace"],
    useCases: ["Audiobook production", "Video voiceovers and narration", "Podcast content creation", "Accessibility and screen readers"],
    pros: ["Most natural-sounding AI voices", "Excellent voice cloning quality", "Wide language support", "Affordable entry pricing"],
    cons: ["Character limits on lower tiers", "Voice cloning requires consent verification", "Some voices have occasional artifacts"],
    platforms: ["Web", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/elevenlabsio",
    discordUrl: "https://discord.gg/elevenlabs",
  },
  {
    name: "Gamma",
    slug: "gamma",
    description: "A new medium for presenting ideas. Powered by AI. Create beautiful, engaging content with none of the formatting and design work.",
    longDescription: "Gamma reimagines presentations by using AI to generate beautiful, interactive slides from a simple prompt or document. Unlike traditional slide tools, Gamma creates web-native presentations that look great on any device, with built-in analytics and engagement tracking.",
    category: "Productivity",
    tags: ["Presentations", "Design", "Slides"],
    websiteUrl: "https://gamma.app",
    logoUrl: "https://logos.hunter.io/gamma.app",
    pricing: "Freemium",
    pricingDetails: "Free tier with 400 AI credits. Plus $10/mo, Pro $20/mo with unlimited AI and analytics.",
    upvotes: 680,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI-generated presentations from prompts", "Web-native interactive format", "Custom themes and branding", "Built-in analytics", "Nested card layouts", "One-click restructuring"],
    useCases: ["Sales decks and pitches", "Internal team updates", "Educational content", "Project proposals"],
    pros: ["Beautiful default designs", "No design skills needed", "Interactive web format", "Fast content creation"],
    cons: ["Less control than PowerPoint", "Limited offline support", "Export options could be better"],
    platforms: ["Web"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/MeetGamma",
  },
  {
    name: "Phind",
    slug: "phind",
    description: "The AI search engine for developers.",
    longDescription: "Phind is an AI-powered search engine specifically designed for developers. It combines web search with AI analysis to provide code-focused answers with explanations, code examples, and relevant documentation links. It's particularly strong at debugging and explaining complex technical concepts.",
    category: "Coding",
    tags: ["Search", "Development", "Assistant"],
    websiteUrl: "https://www.phind.com",
    logoUrl: "https://logos.hunter.io/phind.com",
    pricing: "Free",
    pricingDetails: "Completely free for basic search. Pro $15/mo for faster responses and priority access.",
    upvotes: 540,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Developer-focused AI search", "Code examples in responses", "Source citations", "Follow-up questions", "VS Code extension", "Pair programming mode"],
    useCases: ["Debugging and error resolution", "Learning new APIs and frameworks", "Code review assistance", "Technical documentation search"],
    pros: ["Free to use", "Developer-optimized results", "Fast response times", "Good source citations"],
    cons: ["Less capable than ChatGPT for general tasks", "Smaller model compared to competitors", "Limited non-coding use cases"],
    platforms: ["Web", "Desktop"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/paborhind",
  },
  {
    name: "Leonardo AI",
    slug: "leonardo-ai",
    description: "Create production-quality visual assets for your projects with unprecedented quality, speed, and style-consistency.",
    longDescription: "Leonardo AI specializes in generating game assets, concept art, and production-quality visuals. Its Phoenix model delivers consistent style across multiple generations, making it ideal for game developers and designers who need cohesive visual sets. The platform includes fine-tuning and training capabilities.",
    category: "Image",
    tags: ["Generative Art", "Gaming", "Design"],
    websiteUrl: "https://leonardo.ai",
    logoUrl: "https://logos.hunter.io/leonardo.ai",
    pricing: "Freemium",
    pricingDetails: "Free tier (150 tokens/day). Apprentice $12/mo, Artisan $30/mo, Maestro $60/mo.",
    upvotes: 760,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Phoenix foundation model", "Style-consistent generation", "Real-time canvas editing", "Custom model fine-tuning", "Motion generation", "Texture and 3D asset creation"],
    useCases: ["Game asset creation", "Concept art development", "Marketing visual production", "Texture and material design"],
    pros: ["Excellent for game assets", "Style consistency across sets", "Model training capability", "Generous free tier"],
    cons: ["Token system can be confusing", "UI can be overwhelming", "Less artistic than Midjourney"],
    platforms: ["Web", "iOS", "Android", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/LeonardoAi_",
    discordUrl: "https://discord.gg/leonardoai",
  },
  {
    name: "Suno",
    slug: "suno",
    description: "Make a song about anything. Suno is building a future where anyone can make great music.",
    longDescription: "Suno uses AI to generate full songs with vocals, instruments, and lyrics from simple text prompts. It can create music in virtually any genre and style, complete with coherent song structures. The latest v3.5 model produces radio-quality tracks up to 4 minutes long.",
    category: "Audio",
    tags: ["Music", "Generative Audio", "Creative"],
    websiteUrl: "https://suno.com",
    logoUrl: "https://logos.hunter.io/suno.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (10 songs/day). Pro $10/mo (500 songs/mo), Premier $30/mo (2000 songs/mo).",
    upvotes: 810,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["Full song generation with vocals", "Custom lyrics input", "Multiple genre support", "Extend and remix songs", "Up to 4-minute tracks", "Commercial usage rights on paid plans"],
    useCases: ["Background music for videos", "Jingle and ad creation", "Songwriting inspiration", "Podcast intros and outros"],
    pros: ["Impressive vocal quality", "Easy to use interface", "Wide genre variety", "Fast generation speed"],
    cons: ["Lyrics can be repetitive", "Limited fine control over arrangement", "Vocal clarity varies"],
    platforms: ["Web"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/saboruno_ai_",
    discordUrl: "https://discord.gg/suno-ai",
  },
  {
    name: "Framer AI",
    slug: "framer-ai",
    description: "Generate and publish your site with AI in seconds.",
    longDescription: "Framer AI allows you to describe a website in natural language and generates a fully functional, responsive website in seconds. It combines AI-generated layouts with Framer's powerful no-code editor, letting you refine every detail. Sites are published on Framer's hosting with custom domains.",
    category: "Design",
    tags: ["Web Design", "No-Code", "UI"],
    websiteUrl: "https://www.framer.com/ai",
    logoUrl: "https://logos.hunter.io/framer.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (2 pages, framer.site domain). Mini $5/mo, Basic $15/mo, Pro $25/mo.",
    upvotes: 620,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI website generation from text", "Responsive design output", "Built-in CMS", "Custom domain support", "SEO optimization tools", "Animation and interaction builder"],
    useCases: ["Landing page creation", "Portfolio websites", "Marketing microsites", "Startup websites"],
    pros: ["Incredibly fast site creation", "Beautiful default designs", "Full no-code editor", "Great hosting included"],
    cons: ["Limited AI customization depth", "CMS can be basic", "Vendor lock-in on hosting"],
    platforms: ["Web"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/frabormer",
  },
  {
    name: "Copy.ai",
    slug: "copy-ai",
    description: "Whatever you want to ask, our chat has the answers. Get your work done faster with Copy.ai.",
    longDescription: "Copy.ai is an AI-powered platform focused on go-to-market teams. It combines AI chat, workflow automation, and content generation to help sales and marketing teams create copy, emails, and campaigns faster. The workflow builder automates repetitive content tasks at scale.",
    category: "Writing",
    tags: ["Copywriting", "Marketing", "Sales"],
    websiteUrl: "https://www.copy.ai",
    logoUrl: "https://logos.hunter.io/copy.ai",
    pricing: "Freemium",
    pricingDetails: "Free tier (2000 words/mo). Pro $49/mo (unlimited), Team $249/mo (5 seats), Enterprise custom.",
    upvotes: 510,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI chat for content creation", "Workflow automation builder", "90+ content templates", "Brand voice settings", "Infobase knowledge management", "CRM integrations"],
    useCases: ["Sales outreach emails", "Ad copy and landing pages", "Blog content creation", "Social media posts"],
    pros: ["Good template variety", "Workflow automation", "Free tier available", "Sales-focused features"],
    cons: ["Free tier very limited", "Quality inconsistent on complex tasks", "Expensive for small teams"],
    platforms: ["Web", "Chrome Extension", "API"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/copy_ai",
  },
  {
    name: "Beautiful.ai",
    slug: "beautiful-ai",
    description: "Presentation software that designs for you.",
    longDescription: "Beautiful.ai uses AI to automatically apply design rules as you build presentations. It ensures every slide looks professional with smart templates, automatic spacing, and design guardrails. The AI can also generate entire presentations from a topic or outline.",
    category: "Productivity",
    tags: ["Presentations", "Design", "Slides"],
    websiteUrl: "https://www.beautiful.ai",
    logoUrl: "https://logos.hunter.io/beautiful.ai",
    pricing: "Paid",
    pricingDetails: "Pro $12/mo, Team $40/user/mo, Enterprise custom pricing.",
    upvotes: 430,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI-powered design rules", "Smart slide templates", "DesignerBot AI generation", "Team collaboration", "Brand controls", "PowerPoint export"],
    useCases: ["Business presentations", "Investor pitch decks", "Sales proposals", "Company all-hands"],
    pros: ["Always looks professional", "Very easy to use", "Good template library", "PowerPoint export"],
    cons: ["Less flexible than PowerPoint", "No free tier", "Limited animation options"],
    platforms: ["Web"],
    lastUpdated: "December 2025",
    twitterUrl: "https://twitter.com/beautifulai",
  },
  {
    name: "Gemini",
    slug: "gemini",
    description: "Google's most capable AI model. Get help with writing, planning, learning, and more.",
    longDescription: "Gemini is Google's flagship multimodal AI model, capable of understanding and generating text, images, audio, and video. It integrates deeply with Google Workspace, allowing it to access Gmail, Drive, Docs, and Calendar. The Ultra model rivals GPT-4 in benchmarks.",
    category: "Writing",
    tags: ["LLM", "Chatbot", "Multimodal"],
    websiteUrl: "https://gemini.google.com",
    logoUrl: "https://logos.hunter.io/google.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with Gemini Pro. Advanced $20/mo (Gemini Ultra + 2TB storage). Business $20/user/mo.",
    upvotes: 1320,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["Multimodal understanding", "Google Workspace integration", "Image generation built-in", "Real-time information access", "Code generation and analysis", "Extensions for Google services"],
    useCases: ["Email drafting in Gmail", "Document analysis in Drive", "Research with web access", "Image understanding and generation"],
    pros: ["Deep Google ecosystem integration", "Free tier is generous", "Strong multimodal capabilities", "Access to real-time information"],
    cons: ["Can be inconsistent in quality", "Less capable at coding than Claude/GPT", "Privacy concerns with Google data"],
    platforms: ["Web", "iOS", "Android", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/GoogleaborAI",
  },
  {
    name: "Stable Diffusion",
    slug: "stable-diffusion",
    description: "Open-source deep learning text-to-image model for generating detailed images from text descriptions.",
    longDescription: "Stable Diffusion is the leading open-source image generation model by Stability AI. It can be run locally on consumer hardware, giving users full control over their image generation pipeline. The community has built thousands of fine-tuned models, LoRAs, and extensions around it.",
    category: "Image",
    tags: ["Open Source", "Text-to-Image", "Generative Art"],
    websiteUrl: "https://stability.ai",
    logoUrl: "https://logos.hunter.io/stability.ai",
    pricing: "Free",
    pricingDetails: "Open-source and free to run locally. DreamStudio hosted service: $10 for 1000 credits.",
    upvotes: 1150,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Open-source model weights", "Run locally on consumer GPUs", "SDXL and SD3 models", "Thousands of community models", "ControlNet and LoRA support", "Inpainting and img2img"],
    useCases: ["Custom image generation pipelines", "Game and app asset creation", "Art and illustration", "Research and experimentation"],
    pros: ["Completely free and open-source", "Run locally with full privacy", "Massive community ecosystem", "Highly customizable"],
    cons: ["Requires GPU and technical setup", "Base model less polished than Midjourney", "No user-friendly interface by default"],
    platforms: ["Desktop", "Web", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/StabilityAI",
    githubUrl: "https://github.com/Stability-AI/stablediffusion",
    discordUrl: "https://discord.gg/stablediffusion",
  },
  {
    name: "Udio",
    slug: "udio",
    description: "AI music generation platform that creates high-quality, full-length songs from text descriptions.",
    longDescription: "Udio is a music generation platform that creates high-fidelity songs from text prompts. It supports a wide range of genres and can produce songs with realistic vocals, complex arrangements, and professional mixing. Users can extend, remix, and customize their generated tracks.",
    category: "Audio",
    tags: ["Music", "Generative Audio", "Creative"],
    websiteUrl: "https://www.udio.com",
    logoUrl: "https://logos.hunter.io/udio.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (10 songs/day). Standard $10/mo (1200 songs/mo), Pro $30/mo (unlimited).",
    upvotes: 740,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: true,
    features: ["High-fidelity music generation", "Wide genre support", "Custom lyrics input", "Song extension and remixing", "Audio inpainting", "Shareable track pages"],
    useCases: ["Music production demos", "Content creator background music", "Ad and jingle creation", "Musical experimentation"],
    pros: ["Excellent audio quality", "Diverse genre coverage", "Good vocal synthesis", "Easy to iterate"],
    cons: ["Limited fine control", "Generation can be slow", "Some genres better than others"],
    platforms: ["Web"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/udioabormusic",
    discordUrl: "https://discord.gg/udio",
  },
  {
    name: "Bolt",
    slug: "bolt",
    description: "Build full-stack web applications from a prompt. AI-powered development in your browser.",
    longDescription: "Bolt by StackBlitz lets you describe a web application in natural language and generates a complete full-stack project in your browser. It uses WebContainers to run Node.js entirely in the browser, providing instant previews, package installation, and deployment without any local setup.",
    category: "Coding",
    tags: ["Full-Stack", "No-Code", "Web Development"],
    websiteUrl: "https://bolt.new",
    logoUrl: "https://logos.hunter.io/bolt.new",
    pricing: "Freemium",
    pricingDetails: "Free tier with limited generations. Pro $20/mo for unlimited prompts and deployments.",
    upvotes: 870,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["Full-stack app from prompt", "Browser-based development", "Instant live preview", "One-click deployment", "Package manager built-in", "Multi-file project generation"],
    useCases: ["Rapid application prototyping", "MVP development", "Learning web development", "Hackathon projects"],
    pros: ["No local setup needed", "Full-stack generation", "Instant preview and deploy", "Impressive code quality"],
    cons: ["Complex apps need manual refinement", "Browser-based has limitations", "Limited backend framework options"],
    platforms: ["Web"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/stackaborblitz",
  },
  {
    name: "Replit Agent",
    slug: "replit-agent",
    description: "AI-powered coding assistant that can build entire applications from natural language prompts.",
    longDescription: "Replit Agent is an AI assistant within the Replit IDE that can build full applications from natural language descriptions. It sets up databases, installs packages, writes code across multiple files, and deploys applications. It handles the full development lifecycle from planning to production.",
    category: "Coding",
    tags: ["IDE", "Development", "Full-Stack"],
    websiteUrl: "https://replit.com",
    logoUrl: "https://logos.hunter.io/replit.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with basic features. Replit Core $25/mo with Agent access and enhanced compute.",
    upvotes: 650,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: true,
    features: ["Natural language app building", "Automatic database setup", "Package installation", "Multi-file code generation", "Built-in deployment", "Collaborative editing"],
    useCases: ["Building MVPs quickly", "Learning to code with AI", "Internal tool development", "Hackathon rapid development"],
    pros: ["End-to-end app development", "Built-in hosting and deployment", "Good for beginners", "Collaborative features"],
    cons: ["Can struggle with complex architectures", "Replit environment limitations", "Compute resources limited on free tier"],
    platforms: ["Web", "iOS", "Android"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/Replit",
    discordUrl: "https://discord.gg/replit",
  },
  {
    name: "DALL-E 3",
    slug: "dall-e-3",
    description: "OpenAI's latest image generation model that creates realistic images and art from text descriptions.",
    longDescription: "DALL-E 3 is OpenAI's most advanced image generation model, integrated directly into ChatGPT. It excels at understanding complex prompts, rendering text in images accurately, and following detailed compositional instructions. It produces high-quality, photorealistic images across diverse styles.",
    category: "Image",
    tags: ["Text-to-Image", "Generative Art", "Creative"],
    websiteUrl: "https://openai.com/dall-e-3",
    logoUrl: "https://logos.hunter.io/openai.com",
    pricing: "Paid",
    pricingDetails: "Included with ChatGPT Plus ($20/mo). API pricing from $0.040/image (standard quality).",
    upvotes: 1080,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
    features: ["Accurate text rendering in images", "Complex prompt understanding", "ChatGPT integration", "Multiple aspect ratios", "High resolution output", "Safety filtering"],
    useCases: ["Marketing and advertising visuals", "Social media content", "Illustrations for articles", "Concept visualization"],
    pros: ["Best text-in-image rendering", "Excellent prompt following", "ChatGPT conversation flow", "Consistent quality"],
    cons: ["No direct editing or inpainting", "Requires ChatGPT Plus", "Style less artistic than Midjourney"],
    platforms: ["Web", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/OpenAI",
  },
  {
    name: "Canva AI",
    slug: "canva-ai",
    description: "AI-powered design tools within Canva. Generate images, write copy, resize designs, and more with Magic Studio.",
    longDescription: "Canva's Magic Studio brings AI to the world's most popular design platform. It includes Magic Design for template generation, Magic Write for copy, Magic Edit for image manipulation, and Magic Animate for motion. It makes professional design accessible to everyone.",
    category: "Design",
    tags: ["Graphic Design", "Templates", "Creative"],
    websiteUrl: "https://www.canva.com/ai-image-generator",
    logoUrl: "https://logos.hunter.io/canva.com",
    pricing: "Freemium",
    pricingDetails: "Free tier with limited AI uses. Pro $13/mo (unlimited AI), Teams $10/person/mo, Enterprise custom.",
    upvotes: 960,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Magic Design template generation", "Magic Edit image manipulation", "Magic Write AI copywriting", "Background removal", "Magic Animate motion design", "Brand Kit consistency"],
    useCases: ["Social media graphics", "Presentation design", "Marketing materials", "Video and animation"],
    pros: ["Intuitive for non-designers", "Massive template library", "All-in-one design platform", "Affordable pricing"],
    cons: ["AI features can be basic", "Less control than Photoshop", "Premium templates require Pro"],
    platforms: ["Web", "iOS", "Android", "Desktop"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/canva",
  },
  {
    name: "Luma AI",
    slug: "luma-ai",
    description: "Capture and share lifelike 3D scenes with your phone. Create stunning 3D models from photos and video.",
    longDescription: "Luma AI specializes in 3D capture and generation using Neural Radiance Fields (NeRF) technology. Its Dream Machine can generate 3D scenes from text or images, while its capture app creates photorealistic 3D scans from phone video. It also offers video generation capabilities.",
    category: "Video",
    tags: ["3D", "NeRF", "Capture"],
    websiteUrl: "https://lumalabs.ai",
    logoUrl: "https://logos.hunter.io/lumalabs.ai",
    pricing: "Freemium",
    pricingDetails: "Free tier with limited generations. Pro plans start at $30/mo for more compute and features.",
    upvotes: 580,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["3D scene capture from phone", "Text-to-3D generation", "Dream Machine video generation", "NeRF rendering", "Interactive 3D viewer", "Export to 3D formats"],
    useCases: ["Product 3D visualization", "Real estate virtual tours", "Game asset scanning", "AR/VR content creation"],
    pros: ["Impressive 3D capture quality", "Easy phone-based scanning", "Free tier available", "Fast processing"],
    cons: ["3D generation still maturing", "Limited export formats", "Requires good lighting for best results"],
    platforms: ["Web", "iOS", "API"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/LumaLabsAI",
    discordUrl: "https://discord.gg/lumalabs",
  },
  {
    name: "Grammarly AI",
    slug: "grammarly-ai",
    description: "AI-powered writing assistant that helps you compose bold, clear, mistake-free writing.",
    longDescription: "Grammarly uses AI to check grammar, spelling, tone, and style in real-time across all your writing. The generative AI features can rewrite, expand, and adjust tone of any text. It works everywhere you write through browser extensions, desktop apps, and keyboard integrations.",
    category: "Writing",
    tags: ["Grammar", "Writing Assistant", "Productivity"],
    websiteUrl: "https://www.grammarly.com",
    logoUrl: "https://logos.hunter.io/grammarly.com",
    pricing: "Freemium",
    pricingDetails: "Free basic grammar checks. Premium $12/mo, Business $15/member/mo.",
    upvotes: 1400,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Real-time grammar and spelling", "Tone detection and adjustment", "Generative AI rewriting", "Plagiarism detection", "Style and clarity suggestions", "Works across all apps"],
    useCases: ["Professional email writing", "Academic paper editing", "Content marketing copy", "Non-native English writing"],
    pros: ["Works everywhere you type", "Excellent grammar detection", "Tone and style guidance", "Generous free tier"],
    cons: ["Premium needed for full features", "Can be overly aggressive with suggestions", "Some false positives"],
    platforms: ["Web", "iOS", "Android", "Desktop", "Chrome Extension"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/Grammarly",
  },
  {
    name: "Figma AI",
    slug: "figma-ai",
    description: "AI-powered features in Figma that help you design faster with smart suggestions and auto-layout.",
    longDescription: "Figma AI integrates artificial intelligence directly into the design workflow. Features include AI-generated layouts, content population, layer renaming, and design system suggestions. It understands design context to make intelligent recommendations that speed up the entire design process.",
    category: "Design",
    tags: ["UI Design", "Prototyping", "Collaboration"],
    websiteUrl: "https://www.figma.com",
    logoUrl: "https://logos.hunter.io/figma.com",
    pricing: "Freemium",
    pricingDetails: "Free for individuals (3 projects). Professional $15/editor/mo, Organization $45/editor/mo.",
    upvotes: 920,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
    features: ["AI-powered layout suggestions", "Auto-populate with realistic content", "Smart layer renaming", "Design system recommendations", "Prototype flow generation", "Visual search across files"],
    useCases: ["UI/UX design workflows", "Design system creation", "Rapid prototyping", "Team collaboration on designs"],
    pros: ["Industry-standard design tool", "Seamless AI integration", "Real-time collaboration", "Extensive plugin ecosystem"],
    cons: ["AI features still evolving", "Can be slow with large files", "Learning curve for advanced features"],
    platforms: ["Web", "Desktop"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/figma",
  },
  {
    name: "Pika",
    slug: "pika",
    description: "Create and edit videos with AI. Turn your ideas into stunning videos in seconds.",
    longDescription: "Pika is an AI video generation and editing platform that creates videos from text, images, or existing video. It offers unique editing features like Modify Region for selective edits, Lip Sync for matching audio, and Expand Canvas for changing aspect ratios while maintaining context.",
    category: "Video",
    tags: ["Text-to-Video", "Editing", "Creative"],
    websiteUrl: "https://pika.art",
    logoUrl: "https://logos.hunter.io/pika.art",
    pricing: "Freemium",
    pricingDetails: "Free tier (250 credits). Standard $8/mo (700 credits), Pro $28/mo (2000 credits), Unlimited $58/mo.",
    upvotes: 690,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: true,
    features: ["Text-to-video generation", "Image-to-video animation", "Modify Region selective editing", "Lip Sync feature", "Expand Canvas", "Multiple aspect ratios"],
    useCases: ["Social media video content", "Product animation demos", "Creative video experiments", "Marketing video clips"],
    pros: ["Affordable pricing", "Unique editing features", "Fast generation", "Good quality output"],
    cons: ["Short video length limit", "Can produce artifacts", "Limited resolution options"],
    platforms: ["Web"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/pika_labs",
    discordUrl: "https://discord.gg/pika",
  },
  {
    name: "Whisper",
    slug: "whisper",
    description: "OpenAI's open-source automatic speech recognition system that approaches human-level robustness and accuracy.",
    longDescription: "Whisper is OpenAI's open-source speech recognition model trained on 680,000 hours of multilingual audio. It performs automatic speech recognition, language identification, and translation. The model can be run locally and is widely integrated into other applications and services.",
    category: "Audio",
    tags: ["Speech-to-Text", "Transcription", "Open Source"],
    websiteUrl: "https://openai.com/research/whisper",
    logoUrl: "https://logos.hunter.io/openai.com",
    pricing: "Free",
    pricingDetails: "Completely free and open-source. API access via OpenAI at $0.006/minute.",
    upvotes: 870,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Near human-level accuracy", "99 language support", "Automatic language detection", "Translation capabilities", "Multiple model sizes", "Run locally on device"],
    useCases: ["Meeting transcription", "Podcast and video subtitles", "Voice note transcription", "Multilingual audio processing"],
    pros: ["Free and open-source", "Excellent accuracy", "Massive language support", "Can run offline"],
    cons: ["Requires technical setup for local use", "No real-time streaming in base model", "Large model requires good hardware"],
    platforms: ["Desktop", "API"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/OpenAI",
    githubUrl: "https://github.com/openai/whisper",
  },
  {
    name: "Tabnine",
    slug: "tabnine",
    description: "AI assistant that speeds up delivery and keeps your code safe. Whole-line and full-function code completions.",
    longDescription: "Tabnine is an AI code completion tool that prioritizes privacy and security. It can run entirely on-premise or in isolated cloud environments, making it ideal for enterprises with strict security requirements. It supports all major IDEs and programming languages with context-aware completions.",
    category: "Coding",
    tags: ["Code Completion", "IDE Plugin", "Development"],
    websiteUrl: "https://www.tabnine.com",
    logoUrl: "https://logos.hunter.io/tabnine.com",
    pricing: "Freemium",
    pricingDetails: "Free basic completions. Pro $12/mo, Enterprise custom pricing with on-premise option.",
    upvotes: 520,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Whole-line code completion", "Full-function generation", "On-premise deployment option", "All major IDE support", "Custom model training", "Code chat assistant"],
    useCases: ["Enterprise code development", "Secure coding environments", "Legacy codebase maintenance", "Team productivity boost"],
    pros: ["Strong privacy and security", "On-premise option", "Wide IDE support", "Respects code licensing"],
    cons: ["Less capable than Copilot", "Free tier is basic", "Smaller model than competitors"],
    platforms: ["Desktop"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/Tabnine",
  },
  {
    name: "Otter.ai",
    slug: "otter-ai",
    description: "AI meeting assistant that records audio, writes notes, automatically captures slides, and generates summaries.",
    longDescription: "Otter.ai is an AI meeting assistant that joins your virtual meetings to automatically record, transcribe, and summarize discussions. It identifies speakers, captures key points, extracts action items, and integrates with popular meeting platforms like Zoom, Google Meet, and Teams.",
    category: "Productivity",
    tags: ["Meeting Notes", "Transcription", "Collaboration"],
    websiteUrl: "https://otter.ai",
    logoUrl: "https://logos.hunter.io/otter.ai",
    pricing: "Freemium",
    pricingDetails: "Free tier (300 minutes/mo). Pro $17/mo, Business $30/user/mo, Enterprise custom.",
    upvotes: 780,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Automatic meeting transcription", "Speaker identification", "Action item extraction", "Slide capture", "Meeting summary generation", "Zoom/Meet/Teams integration"],
    useCases: ["Meeting documentation", "Interview transcription", "Lecture note-taking", "Sales call analysis"],
    pros: ["Excellent meeting integration", "Good speaker identification", "Automatic summaries", "Searchable transcripts"],
    cons: ["Free tier minutes are limited", "Accuracy drops with background noise", "Privacy concerns with recording"],
    platforms: ["Web", "iOS", "Android"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/aborotterai",
  },
  {
    name: "Writesonic",
    slug: "writesonic",
    description: "AI writer that creates SEO-optimized content for blogs, ads, emails, and websites 10x faster.",
    longDescription: "Writesonic is an AI writing platform focused on SEO content creation. It includes Chatsonic (an AI chat with web access), an article writer that creates long-form SEO content, and tools for ads, emails, and product descriptions. It's particularly strong for marketing teams.",
    category: "Writing",
    tags: ["SEO", "Blog Writing", "Marketing"],
    websiteUrl: "https://writesonic.com",
    logoUrl: "https://logos.hunter.io/writesonic.com",
    pricing: "Freemium",
    pricingDetails: "Free trial (10K words). Individual $16/mo (100K words), Team $13/user/mo, Enterprise custom.",
    upvotes: 460,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["SEO article writer", "Chatsonic AI chat", "Ad copy generator", "Landing page builder", "Brand voice customization", "Real-time web search"],
    useCases: ["SEO blog content", "Ad copy creation", "Product descriptions", "Email marketing"],
    pros: ["Good SEO optimization", "Multiple content tools", "Affordable pricing", "Brand voice feature"],
    cons: ["Quality varies by topic", "Can produce generic content", "Interface can be cluttered"],
    platforms: ["Web", "Chrome Extension", "API"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/Writesonic",
  },
  {
    name: "Ideogram",
    slug: "ideogram",
    description: "AI image generator with exceptional text rendering capabilities and creative image generation.",
    longDescription: "Ideogram stands out for its ability to render text accurately within AI-generated images — a challenge most other models struggle with. It also produces creative, high-quality images with a distinctive aesthetic style, making it popular for logos, posters, and designs that require readable text.",
    category: "Image",
    tags: ["Text-to-Image", "Typography", "Generative Art"],
    websiteUrl: "https://ideogram.ai",
    logoUrl: "https://logos.hunter.io/ideogram.ai",
    pricing: "Freemium",
    pricingDetails: "Free tier (10 prompts/day). Basic $8/mo (400 prompts), Plus $20/mo (1000 prompts), Pro $60/mo.",
    upvotes: 670,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: true,
    features: ["Accurate text rendering in images", "Creative style generation", "Multiple model options", "Magic Prompt enhancement", "Color palette control", "Negative prompts"],
    useCases: ["Logo and branding design", "Poster and flyer creation", "Social media graphics with text", "T-shirt and merchandise design"],
    pros: ["Best-in-class text rendering", "Creative unique aesthetic", "Generous free tier", "Fast generation"],
    cons: ["Less photorealistic than DALL-E", "Smaller community", "Limited editing capabilities"],
    platforms: ["Web", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/ideaborogram",
  },
  {
    name: "Codeium",
    slug: "codeium",
    description: "Free AI-powered code completion and chat. Modern coding superpowers for every developer.",
    longDescription: "Codeium provides AI code completion and chat completely free for individual developers. It supports over 70 languages and integrates with 40+ IDEs. Unlike competitors, the core product remains free without usage limits, making it accessible to developers worldwide.",
    category: "Coding",
    tags: ["Code Completion", "Free", "IDE Plugin"],
    websiteUrl: "https://codeium.com",
    logoUrl: "https://logos.hunter.io/codeium.com",
    pricing: "Free",
    pricingDetails: "Free for individual developers with unlimited completions. Teams $15/user/mo, Enterprise custom.",
    upvotes: 610,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Unlimited free code completions", "AI chat for code questions", "70+ language support", "40+ IDE integrations", "Codebase-aware context", "In-editor commands"],
    useCases: ["Daily code writing acceleration", "Learning new programming languages", "Code boilerplate generation", "Quick bug fixes"],
    pros: ["Completely free for individuals", "Wide IDE and language support", "No usage limits", "Good completion quality"],
    cons: ["Less capable than GitHub Copilot", "Limited enterprise features on free", "Chat quality is basic"],
    platforms: ["Desktop", "Web"],
    lastUpdated: "January 2026",
    twitterUrl: "https://twitter.com/codeaboriumdev",
    discordUrl: "https://discord.gg/codeium",
  },
  {
    name: "Tome",
    slug: "tome",
    description: "AI-powered format for work. Generate entire presentations, documents, and landing pages from prompts.",
    longDescription: "Tome is an AI-native storytelling format that goes beyond traditional presentations. It generates rich, interactive pages from prompts, combining text, images, and data visualizations. It's designed for modern work communication where traditional slides feel too limiting.",
    category: "Productivity",
    tags: ["Presentations", "Documents", "Storytelling"],
    websiteUrl: "https://tome.app",
    logoUrl: "https://logos.hunter.io/tome.app",
    pricing: "Freemium",
    pricingDetails: "Free tier with basic features. Pro $16/mo, Enterprise custom pricing.",
    upvotes: 550,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["AI page generation from prompts", "Interactive web-native format", "Built-in image generation", "Data visualization", "Custom themes", "Analytics and tracking"],
    useCases: ["Startup pitch decks", "Product briefs and proposals", "Team updates and reports", "Creative portfolios"],
    pros: ["Beautiful modern format", "AI generates full pages", "Interactive elements built-in", "Easy to share"],
    cons: ["Less familiar than PowerPoint", "Limited export options", "Learning curve for format"],
    platforms: ["Web", "iOS"],
    lastUpdated: "December 2025",
    twitterUrl: "https://twitter.com/taborome",
  },
  {
    name: "HeyGen",
    slug: "heygen",
    description: "AI video generation platform for creating professional videos with AI avatars and voice cloning.",
    longDescription: "HeyGen creates professional videos using AI avatars that can speak in 40+ languages with lip-sync accuracy. It offers instant avatar creation from a photo, real-time avatar streaming, and video translation that matches lip movements to new languages. Popular for sales, training, and marketing.",
    category: "Video",
    tags: ["AI Avatars", "Video Generation", "Marketing"],
    websiteUrl: "https://www.heygen.com",
    logoUrl: "https://logos.hunter.io/heygen.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (1 credit). Creator $24/mo (15 credits), Business $72/mo (30 credits), Enterprise custom.",
    upvotes: 730,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["100+ stock AI avatars", "Instant avatar from photo", "Video translation with lip sync", "Streaming avatar for live", "Voice cloning", "Template library"],
    useCases: ["Sales outreach videos", "Training and onboarding", "Multilingual marketing", "Personalized video messages"],
    pros: ["Realistic avatar quality", "Excellent lip sync", "Video translation feature", "Easy to use"],
    cons: ["Credits can be expensive", "Custom avatars cost extra", "Limited video length per credit"],
    platforms: ["Web", "API"],
    lastUpdated: "February 2026",
    twitterUrl: "https://twitter.com/HeyGen_Official",
  },
  {
    name: "Adobe Firefly",
    slug: "adobe-firefly",
    description: "Adobe's generative AI models designed to be safe for commercial use. Generate images, text effects, and more.",
    longDescription: "Adobe Firefly is Adobe's family of generative AI models trained on licensed content, Adobe Stock, and public domain works. This makes it safe for commercial use without copyright concerns. It's integrated across Adobe's Creative Cloud apps including Photoshop, Illustrator, and Express.",
    category: "Image",
    tags: ["Generative Art", "Commercial", "Adobe"],
    websiteUrl: "https://www.adobe.com/products/firefly.html",
    logoUrl: "https://logos.hunter.io/adobe.com",
    pricing: "Freemium",
    pricingDetails: "Free tier (25 credits/mo). Premium $10/mo (100 credits). Included with Creative Cloud subscriptions.",
    upvotes: 890,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
    features: ["Commercially safe AI generation", "Photoshop Generative Fill", "Text effects generation", "Style reference matching", "Structure reference", "Integrated across Creative Cloud"],
    useCases: ["Commercial design projects", "Photo editing and compositing", "Brand asset creation", "Marketing material design"],
    pros: ["Commercially safe to use", "Deep Adobe integration", "Photoshop Generative Fill is excellent", "IP indemnification"],
    cons: ["Credit system is limiting", "Less creative than Midjourney", "Requires Adobe ecosystem"],
    platforms: ["Web", "Desktop", "API"],
    lastUpdated: "March 2026",
    twitterUrl: "https://twitter.com/AdobeFirefly",
  },
];

export const seed = mutation({
  handler: async (ctx: any) => {
    const existing = await ctx.db.query("tools").collect();
    if (existing.length > 0) {
      return `Already seeded (${existing.length} tools exist). Use Reseed to replace with fresh data.`;
    }

    let time = Date.now();
    for (const tool of toolsData) {
      await ctx.db.insert("tools", {
        ...tool,
        createdAt: time--,
      });
    }

    return `Seeded ${toolsData.length} AI tools successfully`;
  },
});

export const reseed = mutation({
  handler: async (ctx: any) => {
    const existing = await ctx.db.query("tools").collect();
    for (const tool of existing) {
      await ctx.db.delete(tool._id);
    }

    const reviews = await ctx.db.query("reviews").collect();
    for (const review of reviews) {
      await ctx.db.delete(review._id);
    }
    const bookmarks = await ctx.db.query("bookmarks").collect();
    for (const bookmark of bookmarks) {
      await ctx.db.delete(bookmark._id);
    }

    let time = Date.now();
    for (const tool of toolsData) {
      await ctx.db.insert("tools", {
        ...tool,
        createdAt: time--,
      });
    }

    return `Cleared ${existing.length} old tools and seeded ${toolsData.length} fresh AI tools`;
  },
});
