import { mutation } from "./_generated/server";

const toolsData = [
  {
    name: "ChatGPT",
    slug: "chatgpt",
    description: "OpenAI's conversational AI model capable of generating human-like text, answering questions, and assisting with various tasks.",
    category: "Writing",
    tags: ["Chatbot", "LLM", "Assistant"],
    websiteUrl: "https://chat.openai.com",
    logoUrl: "https://picsum.photos/seed/chatgpt/200/200",
    pricing: "Freemium",
    upvotes: 1542,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "An AI program and service created by Midjourney, Inc. that generates images from natural language descriptions.",
    category: "Image",
    tags: ["Generative Art", "Design", "Creative"],
    websiteUrl: "https://www.midjourney.com",
    logoUrl: "https://picsum.photos/seed/midjourney/200/200",
    pricing: "Paid",
    upvotes: 1230,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    description: "An AI pair programmer that offers autocomplete-style suggestions as you code.",
    category: "Coding",
    tags: ["Development", "Code Assistant", "Productivity"],
    websiteUrl: "https://github.com/features/copilot",
    logoUrl: "https://picsum.photos/seed/copilot/200/200",
    pricing: "Paid",
    upvotes: 980,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "Notion AI",
    slug: "notion-ai",
    description: "An AI assistant integrated into Notion that helps you write, brainstorm, edit, and summarize.",
    category: "Productivity",
    tags: ["Writing", "Notes", "Workspace"],
    websiteUrl: "https://www.notion.so/product/ai",
    logoUrl: "https://picsum.photos/seed/notionai/200/200",
    pricing: "Paid",
    upvotes: 850,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Runway",
    slug: "runway",
    description: "Applied AI research company shaping the next era of art, entertainment and human creativity.",
    category: "Video",
    tags: ["Video Editing", "Generative Video", "Creative"],
    websiteUrl: "https://runwayml.com",
    logoUrl: "https://picsum.photos/seed/runway/200/200",
    pricing: "Freemium",
    upvotes: 720,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "Claude",
    slug: "claude",
    description: "A next-generation AI assistant built for work and trained to be safe, accurate, and secure.",
    category: "Writing",
    tags: ["Chatbot", "LLM", "Assistant"],
    websiteUrl: "https://claude.ai",
    logoUrl: "https://picsum.photos/seed/claude/200/200",
    pricing: "Freemium",
    upvotes: 1100,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
  },
  {
    name: "Synthesia",
    slug: "synthesia",
    description: "An AI video generation platform that enables you to turn text into video in minutes.",
    category: "Video",
    tags: ["Avatars", "Text-to-Video", "Marketing"],
    websiteUrl: "https://www.synthesia.io",
    logoUrl: "https://picsum.photos/seed/synthesia/200/200",
    pricing: "Paid",
    upvotes: 640,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Jasper",
    slug: "jasper",
    description: "An AI copilot for enterprise marketing teams who want better outcomes, not just faster outputs.",
    category: "Writing",
    tags: ["Marketing", "Copywriting", "SEO"],
    websiteUrl: "https://www.jasper.ai",
    logoUrl: "https://picsum.photos/seed/jasper/200/200",
    pricing: "Paid",
    upvotes: 590,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Cursor",
    slug: "cursor",
    description: "The AI Code Editor. Built to make you extraordinarily productive.",
    category: "Coding",
    tags: ["IDE", "Development", "Code Assistant"],
    websiteUrl: "https://cursor.sh",
    logoUrl: "https://picsum.photos/seed/cursor/200/200",
    pricing: "Freemium",
    upvotes: 890,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
  },
  {
    name: "Descript",
    slug: "descript",
    description: "There's a new way to make video and podcasts. A good way.",
    category: "Video",
    tags: ["Audio", "Editing", "Transcription"],
    websiteUrl: "https://www.descript.com",
    logoUrl: "https://picsum.photos/seed/descript/200/200",
    pricing: "Freemium",
    upvotes: 710,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    description: "Perplexity AI is an AI-chat-based conversational search engine that answers queries using natural language predictive text.",
    category: "Productivity",
    tags: ["Search", "Research", "LLM"],
    websiteUrl: "https://www.perplexity.ai",
    logoUrl: "https://picsum.photos/seed/perplexity/200/200",
    pricing: "Freemium",
    upvotes: 1050,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "V0 by Vercel",
    slug: "v0",
    description: "Generate UI with simple text prompts. v0 is a generative user interface system by Vercel.",
    category: "Coding",
    tags: ["UI", "Design", "React"],
    websiteUrl: "https://v0.dev",
    logoUrl: "https://picsum.photos/seed/v0/200/200",
    pricing: "Freemium",
    upvotes: 820,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
  },
  {
    name: "ElevenLabs",
    slug: "elevenlabs",
    description: "The most realistic AI speech software. Create lifelike voiceovers for your content or use our AI voice generator as an easy-to-use text to speech reader.",
    category: "Audio",
    tags: ["Voice", "Text-to-Speech", "Cloning"],
    websiteUrl: "https://elevenlabs.io",
    logoUrl: "https://picsum.photos/seed/elevenlabs/200/200",
    pricing: "Freemium",
    upvotes: 930,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: false,
  },
  {
    name: "Gamma",
    slug: "gamma",
    description: "A new medium for presenting ideas. Powered by AI. Create beautiful, engaging content with none of the formatting and design work.",
    category: "Productivity",
    tags: ["Presentations", "Design", "Slides"],
    websiteUrl: "https://gamma.app",
    logoUrl: "https://picsum.photos/seed/gamma/200/200",
    pricing: "Freemium",
    upvotes: 680,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Phind",
    slug: "phind",
    description: "The AI search engine for developers.",
    category: "Coding",
    tags: ["Search", "Development", "Assistant"],
    websiteUrl: "https://www.phind.com",
    logoUrl: "https://picsum.photos/seed/phind/200/200",
    pricing: "Free",
    upvotes: 540,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Leonardo AI",
    slug: "leonardo-ai",
    description: "Create production-quality visual assets for your projects with unprecedented quality, speed, and style-consistency.",
    category: "Image",
    tags: ["Generative Art", "Gaming", "Design"],
    websiteUrl: "https://leonardo.ai",
    logoUrl: "https://picsum.photos/seed/leonardo/200/200",
    pricing: "Freemium",
    upvotes: 760,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Suno",
    slug: "suno",
    description: "Make a song about anything. Suno is building a future where anyone can make great music.",
    category: "Audio",
    tags: ["Music", "Generative Audio", "Creative"],
    websiteUrl: "https://suno.com",
    logoUrl: "https://picsum.photos/seed/suno/200/200",
    pricing: "Freemium",
    upvotes: 810,
    submittedBy: "system",
    approved: true,
    featured: true,
    isNew: true,
  },
  {
    name: "Framer AI",
    slug: "framer-ai",
    description: "Generate and publish your site with AI in seconds.",
    category: "Design",
    tags: ["Web Design", "No-Code", "UI"],
    websiteUrl: "https://www.framer.com/ai",
    logoUrl: "https://picsum.photos/seed/framer/200/200",
    pricing: "Freemium",
    upvotes: 620,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Copy.ai",
    slug: "copy-ai",
    description: "Whatever you want to ask, our chat has the answers. Get your work done faster with Copy.ai.",
    category: "Writing",
    tags: ["Copywriting", "Marketing", "Sales"],
    websiteUrl: "https://www.copy.ai",
    logoUrl: "https://picsum.photos/seed/copyai/200/200",
    pricing: "Freemium",
    upvotes: 510,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  },
  {
    name: "Beautiful.ai",
    slug: "beautiful-ai",
    description: "Presentation software that designs for you.",
    category: "Productivity",
    tags: ["Presentations", "Design", "Slides"],
    websiteUrl: "https://www.beautiful.ai",
    logoUrl: "https://picsum.photos/seed/beautifulai/200/200",
    pricing: "Paid",
    upvotes: 430,
    submittedBy: "system",
    approved: true,
    featured: false,
    isNew: false,
  }
];

export const seed = mutation({
  handler: async (ctx: any) => {
    const existing = await ctx.db.query("tools").collect();
    if (existing.length > 0) {
      return "Already seeded";
    }

    let time = Date.now();
    for (const tool of toolsData) {
      await ctx.db.insert("tools", {
        ...tool,
        createdAt: time--,
      });
    }

    return "Seeded successfully";
  },
});
